import { generateAiAuditRoles } from "../ai/geminiAdapter.mjs";
import { detectVulnerabilities } from "../security/detectorEngine.mjs";

const severityWeight = {
  info: 1,
  low: 2,
  medium: 4,
  high: 7,
  critical: 10
};

function makeReportMarkdown({ job, findings, aiRoles }) {
  const findingLines = findings.length
    ? findings.map((finding) => (
      `- [${finding.severity.toUpperCase()}] ${finding.title}` +
      `${finding.line ? ` (line ${finding.line})` : ""}: ${finding.recommendation}`
    )).join("\n")
    : "- No baseline findings detected.";
  const triageLines = aiRoles.triage?.length
    ? aiRoles.triage.map((item) => `- ${item.id}: ${item.severity} / confidence ${item.confidence} - ${item.exploitability}`).join("\n")
    : "- No AI triage items returned.";
  const falsePositiveLines = aiRoles.falsePositiveReview?.length
    ? aiRoles.falsePositiveReview.map((item) => `- ${item.id}: ${item.likelyFalsePositive ? "possible false positive" : "keep open"} - ${item.reason}`).join("\n")
    : "- No AI false-positive review returned.";
  const remediationLines = aiRoles.remediationPlan?.length
    ? aiRoles.remediationPlan.map((item) => `- ${item.id}: ${item.patch} Test: ${item.regressionTest}`).join("\n")
    : "- No AI remediation guidance returned.";

  return [
    `# Audit Report: ${job.target}`,
    "",
    `Chain: ${job.chain}`,
    `Source type: ${job.sourceType}`,
    `Generated: ${new Date().toISOString()}`,
    "",
    "## AI-Assisted Summary",
    aiRoles.summary,
    "",
    "## AI Worker Routing",
    `Primary lane: ${aiRoles.workerRouting?.primaryLane || "review-required"}`,
    `Secondary lane: ${aiRoles.workerRouting?.secondaryLane || "human-security-review"}`,
    `Reason: ${aiRoles.workerRouting?.reason || "No routing reason returned."}`,
    "",
    "## AI Triage",
    triageLines,
    "",
    "## AI False-Positive Review",
    falsePositiveLines,
    "",
    "## AI Remediation Plan",
    remediationLines,
    "",
    "## Executive Report",
    `Risk posture: ${aiRoles.executiveReport?.riskPosture || "Review required."}`,
    `Release gate: ${aiRoles.executiveReport?.releaseGate || "review-before-release"}`,
    aiRoles.executiveReport?.ownerSummary || aiRoles.summary,
    "",
    "## Findings",
    findingLines,
    "",
    "## Review Notes",
    "This report is generated by the baseline static and heuristic detector pipeline. Production sign-off still requires human review."
  ].join("\n");
}

export async function runAuditPipeline(job, options = {}) {
  const started = Date.now();
  const sourceCode = job.sourceCode || job.source || "";

  const emit = async (stage, percent, message, detail = null) => {
    if (typeof options.onProgress === "function") {
      await options.onProgress({ stage, percent, message, detail });
    }
  };

  await emit("parse", 18, "Contract source loaded and normalized", {
    bytes: Buffer.byteLength(sourceCode, "utf8"),
    sourceType: job.sourceType
  });

  const findings = detectVulnerabilities(sourceCode);

  await emit("static-analysis", 42, "Static detector rules completed", {
    findings: findings.length
  });

  const aiRoles = await generateAiAuditRoles({
    sourceCode,
    findings,
    prompts: options.prompts || {}
  });

  await emit("ai-analysis", 68, "AI/LLM routing, triage, false-positive, remediation, and report roles completed", {
    mode: aiRoles.mode,
    model: aiRoles.model,
    routing: aiRoles.workerRouting
  });

  const riskScore = findings.reduce((score, finding) => score + severityWeight[finding.severity], 0);
  const reportMarkdown = makeReportMarkdown({ job, findings, aiRoles });

  await emit("report-generation", 86, "Markdown report generated", {
    riskScore
  });

  return {
    ...job,
    status: "completed",
    findings,
    aiSummary: aiRoles.summary,
    aiMode: aiRoles.mode,
    aiModel: aiRoles.model,
    aiRoles,
    workerRouting: aiRoles.workerRouting,
    triage: aiRoles.triage,
    falsePositiveReview: aiRoles.falsePositiveReview,
    remediationPlan: aiRoles.remediationPlan,
    executiveReport: aiRoles.executiveReport,
    riskScore,
    reportMarkdown,
    updatedAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
    durationMs: Date.now() - started
  };
}
